name: Amplify Environment Variable Generation
description: Generates environment variables for Amplify
inputs:
  environment:
    description: "Name of the environment e.g. dev, staging, prod"
    required: true
  github_token:
    description: "GitHub token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup build environment
      id: setup
      run: |
        # Variables
        environment="${{ inputs.environment }}"
        config_file_name=${{ inputs.environment == 'dev' && 'development' || inputs.environment }}.json
        target_branch=${{ inputs.environment == 'prod' && 'main' || inputs.environment }}

        # Clone Perps Hedger Config GitHub repo
        git clone -b $target_branch https://$GITHUB_TOKEN@github.com/orbs-network/perps-hedger-config.git

        # Python setup and generate environment variables tfvars file
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        python amplify-environment-variable-generation.py --config ./perps-hedger-config/appconfig/$config_file_name --environment $environment
        mv terraform.tfvars ../../../../infrastructure/terraform.tfvars
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      working-directory: ./.github/actions/amplify-environment-variable-generation/amplify-environment-variable-generation
